language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
 
matrix:
    allow_failures:
        - php: hhvm

env:
  - SYMFONY_VERSION=2.0.*
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/http-foundation:${SYMFONY_VERSION}

script: phpunit --coverage-text

notifications:
  email:
    - friendsofsymfony-dev@googlegroups.com
