language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.7.*

before_script:
  - composer require symfony/http-foundation:${SYMFONY_VERSION}

script: phpunit --coverage-text

notifications:
  email:
    - friendsofsymfony-dev@googlegroups.com
